# Generated by Django 3.0.1 on 2022-02-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencynumber',
            fields=[
                ('emgno_id', models.AutoField(primary_key=True, serialize=False)),
                ('emg_no', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('alert', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'emergencynumber',
                'managed': False,
            },
        ),
    ]
