# Generated by Django 3.0.1 on 2022-02-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_id', models.IntegerField()),
                ('to_id', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
    ]
