# Generated by Django 3.0.1 on 2022-02-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reply', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
